[project]
name = "oreilly-live-training-pyats"
version = "0.1.0"
description = "Examples and code for the O'Reilly Live Training course 'Network Testing and Automation'"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "genie>=25.9",
    "pyats>=25.9",
]
