---
mgmt:
  loopbacks:
    Loopback0: 10.254.1.1
    Loopback1: 10.50.0.1

bgp:
  asn: 65000
  networks:
    - { network: 10.50.0.0, mask: 255.255.255.0 }
  neighbors:
    - { neighbor: 172.16.1.2, remote_as: 65001 }
