---
mgmt:
  loopbacks:
    Loopback0: 10.254.1.2
    Loopback1: 10.60.0.1

bgp:
  asn: 65001
  networks:
    - { network: 10.60.0.0, mask: 255.255.255.0 }
  neighbors:
    - { neighbor: 172.16.1.1, remote_as: 65000 }
